export const GET_RETAILERS_START = 'GET_RETAILERS_START';
export const SET_RETAILERS = 'SET_RETAILERS';
export const GET_RETAILERS_SUCCESS = 'GET_RETAILERS_SUCCESS';
export const GET_RETAILERS_FAIL = 'GET_RETAILERS_FAIL';
