export const GET_LATEST_PRODUCTS_START = 'GET_LATEST_PRODUCTS_START';
export const GET_LATEST_PRODUCTS_SUCCESS = 'GET_LATEST_PRODUCTS_SUCCESS';
export const GET_LATEST_PRODUCTS_FAIL = 'GET_LATEST_PRODUCTS_FAIL';
export const SET_LATEST_PRODUCTS = 'SET_LATEST_PRODUCTS';

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';
export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';

export const GET_PRODUCT_BY_ID_START = 'GET_PRODUCT_BY_ID_START';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL';
export const SET_PRODUCT_BY_ID = 'SET_PRODUCT_BY_ID';
