export const GET_LATEST_PRODUCTS_START = 'GET_LATEST_PRODUCTS_START';
export const SET_LATEST_PRODUCTS = 'SET_LATEST_PRODUCTS';
export const GET_LATEST_PRODUCTS_SUCCESS = 'GET_LATEST_PRODUCTS_SUCCESS';
export const GET_LATEST_PRODUCTS_FAIL = 'GET_LATEST_PRODUCTS_FAIL';

export const SEARCH_START = 'SEARCH_START';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
